os:
  - linux
  - osx
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - liblzma-dev
# We want to compile with g++ 4.8 when rather than the default g++
env:
  global:
    - CXX=g++-4.8
  matrix:
    - COMPILE=1
    - ENABLE_MT=1 COMPILE=1
before_install:
  # Install node-gyp and node-pre-gyp so it is available for packaging and publishing
  - npm install node-pre-gyp -g
install:
  # Ensure source install works and compiles correctly
  - npm install
  # test our module
  - npm test
