init:
  plugins:
    - mocha
    - clean
    - packagejson
    - grab
settings:
  exec:
    env:
      CPPFLAGS: "-fPIC"
      CFLAGS: "-O3"
  xzBetaLink: 'http://tukaani.org/xz/xz-5.2.2.tar.gz'
  toDistclean: ['lib', 'build', '*.tar.gz', '*.log']
  srcPath: 'src'
  libPath: 'lib'
  mocha:
    useCoffee: true
clean:
  - node-gyp clean
build_lzma:
  - echo Building LibLZMA from sources !
  - echo Cleaning deps ...
  - rm -rf deps
  - echo Fetching source ...
  - grab: "%xzBetaLink"
  - mkdir -p deps/xz
  - tar zxvf `basename %xzBetaLink` -C deps/xz --strip-components=1
  - cd deps/xz
  - ./autogen.sh
  - ./configure --prefix=`pwd` --enable-threads --enable-static --disable-shared --disable-scripts --disable-lzmainfo
    --disable-lzma-links --disable-lzmadec --disable-xzdec --disable-xz --disable-rpath
  - make
  - make install
  - env: CPATH=`pwd`/include
  - env: LIBRARY_PATH=`pwd`/lib
  - env: LD_LIBRARY_PATH=$LIBRARY_PATH:$LD_LIBRARY_PATH
  - echo Done compiling liblzma. headers are at $CPATH
  - cd ../..
build_module:
  - echo Building %name version %version Add-On ...
  - node-gyp configure build
build:
  - '[ "$COMPILE" = "1" ] && ./node_modules/.bin/ubs build_lzma'
  - task: build_module
  - task: build_coffee
build_coffee:
  - echo Building Javascript API...
  - coffee -b -c -o %libPath %srcPath
  - echo Done building Javascript.
test:
  - task: mocha-test
install:
  - task: build
  - rm *.tar.gz
  - echo Build done.
