init:
  plugins:
    - mocha
    - clean
    - packagejson
    - grab
settings:
  exec:
    env:
      CPPFLAGS: "-fPIC"
      CFLAGS: "-O3"
  xzWebUrl: 'http://tukaani.org/xz'
  xzVersion: '5.2.3'
  xzExt: 'gz'
  clean:
    path: ['lib', '*.log']
    distclean: ['build', 'xz*.tar.*']
  srcPath: 'src'
  libPath: 'lib'
  coffee: './node_modules/.bin/coffee'
  npg: './node_modules/.bin/node-pre-gyp'
  mocha:
    useCoffee: true
clean:
  - '%npg% clean'
  - rm -rf %clean.path%
fetch_lzma:
  - log: Fetching source ...
  - grab: "%xzWebUrl%-%xzVersion%.tar.%xzExt%"
  - mkdir -p deps/xz
  - '[ "%xzExt%" = "gz" ] && tar zxvf xz-%xzVersion%.tar.%xzExt% -C deps/xz --strip-components=1'
  - '[ "%xzExt%" = "bz2" ] && tar jxvf xz-%xzVersion%.tar.%xzExt% -C deps/xz --strip-components=1'
  - '[ "%xzExt%" = "xz" ] && tar Jxvf xz-%xzVersion%.tar.%xzExt% -C deps/xz --strip-components=1'
build_lzma:
  - log: Building LibLZMA from sources !
  - log: Cleaning deps ...
  - rm -rf deps
  - task: fetch_lzma
  - cd deps/xz
  - ./autogen.sh
  - ./configure --prefix=`pwd` --enable-threads --enable-static --disable-shared --disable-scripts --disable-lzmainfo
    --disable-lzma-links --disable-lzmadec --disable-xzdec --disable-xz --disable-rpath
  - make
  - make install
  - env: CPATH=`pwd`/include
  - env: LIBRARY_PATH=`pwd`/lib
  - env: LD_LIBRARY_PATH=$LIBRARY_PATH:$LD_LIBRARY_PATH
  - log: Done compiling liblzma. headers are at $CPATH
  - cd ../..
build_module:
  - log: Building %name% version %version% Add-On ...
  - '%npg% install --fallback-to-build'
  # - node-gyp configure build
build:
  - '[ "$COMPILE" = "1" ] && %ubs% build_lzma xzVersion=%xzVersion% xzExt=%xzExt%'
  - task: build_module
  # If we do not have any coffee file, files should have been already compiled
  - '[ -r %libPath%/lzma.js ] || %ubs% build_coffee'
build_coffee:
  - log: Building Javascript API...
  - '%coffee% -b -c -o %libPath% %srcPath%'
  - log: Done building Javascript.
test:
  - task: mocha-test
install:
  - task: build
  - log: Build done.
